force-app/main/default/objects/XRPForSalesforceSettings__c/XRPForSalesforceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>XRPForSalesforceSettings</label>
</CustomObject>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiKey__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiKey__c</fullName>
    <label>XRPWebhookApiKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiSecret__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiSecret__c</fullName>
    <label>XRPWebhookApiSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetupCtrl_Test.cls
@isTest
private class SetupCtrl_Test {
    @isTest
    static void getSttings_ExistingSettings() {
        XRPForSalesforceSettings__c settings = XRPForSalesforceSettingsService.settings;
        settings.XRPWebhookApiKey__c = 'test_API_Key';
        settings.XRPWebhookApiSecret__c = 'test_API_Secret';
        XRPForSalesforceSettingsService.settings = settings;

        Test.startTest();
        SetupCtrl.Settings result = SetupCtrl.getSettings();
        Test.stopTest();

        Assert.areEqual(result.apiKey, System.Label.settings_api_key_setted);
        Assert.areEqual(result.apiSecret, System.Label.settings_api_secret_setted);
    }

    @isTest
    static void getSttings_NoExistingSettings() {
        XRPForSalesforceSettings__c settings = XRPForSalesforceSettingsService.settings;
        XRPForSalesforceSettingsService.settings = settings;

        Test.startTest();
        SetupCtrl.Settings result = SetupCtrl.getSettings();
        Test.stopTest();

        Assert.areEqual(result.apiKey, null);
        Assert.areEqual(result.apiSecret, null);
    }

    @isTest
    static void saveSettings_SettingsSaved() {
        XRPForSalesforceSettings__c settings = XRPForSalesforceSettingsService.settings;
        XRPForSalesforceSettingsService.settings = settings;

        Test.startTest();
        SetupCtrl.Settings result = SetupCtrl.saveSettings('test_new_API_Key', 'test_new_API_Secret');
        Test.stopTest();

        Assert.areEqual(result.apiKey, System.Label.settings_api_key_setted);
        Assert.areEqual(result.apiSecret, System.Label.settings_api_secret_setted);
    }
}