force-app/main/default/objects/XRPForSalesforceSettings__c/XRPForSalesforceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>XRPForSalesforceSettings</label>
</CustomObject>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiKey__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiKey__c</fullName>
    <label>XRPWebhookApiKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiSecret__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiSecret__c</fullName>
    <label>XRPWebhookApiSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetupCtrl.cls
public with sharing class SetupCtrl {
    @AuraEnabled
    public static Settings getSettings(){
        try {
            XRPForSalesforceSettings__c settings = XRPForSalesforceSettingsService.settings;
            return new Settings(settings.XRPWebhookApiKey__c, settings.XRPWebhookApiSecret__c);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void saveSettings(String apiKey, String apiSecret) {
        try {
            XRPForSalesforceSettings__c settings = XRPForSalesforceSettingsService.settings;

            settings.XRPWebhookApiKey__c = apiKey;
            settings.XRPWebhookApiSecret__c = apiSecret;

            upsert as user settings;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class Settings {
        @AuraEnabled public Boolean apiKey;
        @AuraEnabled public Boolean apiSecret;

        public Settings(){}

        public Settings(String apiKey, String apiSecret){
            this.apiKey = apiKey != null;
            this.apiSecret = apiSecret != null;
        }
    }
}