force-app/main/default/objects/Asset_Token__c/Asset_Token__c.object-meta.xml
<CustomObject>
    <label>Asset-Token</label>
    <nameField>
        <label>Asset Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset-Tokens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Token__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset_Token__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Token Code</description>
    <inlineHelpText>Token Code</inlineHelpText>
    <label>Asset</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset_Token__c/fields/CoinGeckoAPIName__c.field-meta.xml
<CustomField>
    <fullName>CoinGeckoAPIName__c</fullName>
    <description>Coin Gecko API Name</description>
    <label>Coin Gecko API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset_Token__c/fields/ConversionRate__c.field-meta.xml
<CustomField>
    <fullName>ConversionRate__c</fullName>
    <label>Conversion Rate</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset_Token__c/fields/ConversionRateLastSet__c.field-meta.xml
<CustomField>
    <fullName>ConversionRateLastSet__c</fullName>
    <label>Conversion Rate Last Set</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/XRPForSalesforceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>XRPForSalesforceSettings</label>
</CustomObject>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPSiteDomainUrl__c.field-meta.xml
<CustomField>
    <fullName>XRPSiteDomainUrl__c</fullName>
    <label>XRPSiteDomainUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiKey__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiKey__c</fullName>
    <label>XRPWebhookApiKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiSecret__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiSecret__c</fullName>
    <label>XRPWebhookApiSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookId__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookId__c</fullName>
    <label>XRPWebhookId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssetTokenService_Test.cls
@isTest
private class AssetTokenService_Test {
    @isTest
    static void updateRippleAssetTokenExchangeRate_Success() {
        XRPForSalesforceSettings__c settings = new XRPForSalesforceSettings__c();
        settings.XRPWebhookApiKey__c = 'test_webhook_api_key';
        settings.XRPWebhookApiSecret__c = 'test_webhook_api_secret';
        settings.XRPSiteDomainUrl__c = 'test_site_domain';
        settings.XRPWebhookId__c = 'test_webhook_id';
        insert settings;

        Asset_Token__c rippleAssetToken = new Asset_Token__c();
        rippleAssetToken.Name = AssetTokenService.RIPPLE_NAME;
        rippleAssetToken.Asset__c = AssetTokenService.RIPPLE_ASSET;
        rippleAssetToken.Active__c = true;
        rippleAssetToken.CoinGeckoAPIName__c = AssetTokenService.RIPPLE_COIN_GECKO_API_NAME;
        rippleAssetToken.ConversionRate__c = AssetTokenService.RIPPLE_DEFAULT_EXCHANGE_RATE;
        rippleAssetToken.ConversionRateLastSet__c = Datetime.now();
        insert rippleAssetToken;

        Decimal rate = AssetTokenService.RIPPLE_DEFAULT_EXCHANGE_RATE + 0.2;
        String transactionCurrencyCode = 'usd';

        CurrencyService.defaultCurrencyCode = transactionCurrencyCode;
        TestDataFactory.InitializeAssetTokensBody body = new TestDataFactory.InitializeAssetTokensBody(
            rate
        );

        new HttpMock()
            .get(
                String.format(
                    CoinGeckoService.GET_EXCHANGE_RATE_ENDPOINT,
                    new List<String>{
                        AssetTokenService.RIPPLE_COIN_GECKO_API_NAME,
                        transactionCurrencyCode
                    }
                ),
                body,
                200
            )
            .mock();

        Test.startTest();
        List<Decimal> result = AssetTokenService.updateRippleAssetTokenExchangeRate();
        Test.stopTest();

        Assert.areEqual(1, result.size());
        Assert.areEqual(rate, result[0]);
    }
}