force-app/main/default/objects/Org_Wallet__c/Org_Wallet__c.object-meta.xml
<CustomObject>
    <description>Organization&apos;s Web3 Digital Wallet</description>
    <label>Org Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Wallets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Wallet__c/fields/Networks__c.field-meta.xml
<CustomField>
    <fullName>Networks__c</fullName>
    <label>Preferred Networks</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Blockchains</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Org_Wallet__c/fields/Wallet_Address__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Address__c</fullName>
    <description>Publicly available address.</description>
    <label>Wallet Address</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Org_Wallet__c/fields/XRPWebhookSubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookSubscriptionId__c</fullName>
    <label>XRPWebhookSubscriptionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/XRPForSalesforceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>XRPForSalesforceSettings</label>
</CustomObject>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiKey__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiKey__c</fullName>
    <label>XRPWebhookApiKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookApiSecret__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookApiSecret__c</fullName>
    <label>XRPWebhookApiSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/XRPForSalesforceSettings__c/fields/XRPWebhookId__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookId__c</fullName>
    <label>XRPWebhookId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Blockchains.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>XRP_Mainnet</fullName>
        <default>true</default>
        <label>XRP Ledger</label>
    </customValue>
    <customValue>
        <fullName>XRP_Testnet</fullName>
        <label>XRP Testnet</label>
    </customValue>
    <description>Blockchains supported</description>
    <masterLabel>Blockchains</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrgWalletService_Test.cls
@isTest
private class OrgWalletService_Test {
    @isTest
    static void processXRPWebhooks_Success() {
        XRPForSalesforceSettings__c settings = new XRPForSalesforceSettings__c();
        settings.XRPWebhookApiKey__c = 'test_webhook_api_key';
        settings.XRPWebhookApiSecret__c = 'test_webhook_api_secret';
        settings.XRPWebhookId__c = 'test_webhook_id';
        XRPForSalesforceSettingsService.settings = settings;

        XrpWebhookService.RegisterSubscriptionResponse body = new XrpWebhookService.RegisterSubscriptionResponse();
        body.subscription_id = 'test_subscription_id';
        body.success = true;
        
        new HttpMock().post(XrpWebhookService.REGISTER_SUBSCRIPTION_SUFFIX, body, 200).mock();

        Test.startTest();
        Org_Wallet__c wallet = new Org_Wallet__c();
        wallet.Wallet_Address__c = 'test_wallet_address';
        wallet.Networks__c = 'XRP_LEDGER';

        insert wallet;
        Test.stopTest();

        Org_Wallet__c connectedWallet = [SELECT XRPWebhookSubscriptionId__c FROM Org_Wallet__c WHERE Id = :wallet.Id];
        Assert.isNotNull(connectedWallet.XRPWebhookSubscriptionId__c);
    }
}