force-app/main/default/objects/Org_Wallet__c/Org_Wallet__c.object-meta.xml
<CustomObject>
    <description>Organization&apos;s Web3 Digital Wallet</description>
    <label>Org Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Wallets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Wallet__c/fields/Wallet_Address__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Address__c</fullName>
    <description>Publicly available address.</description>
    <label>Wallet Address</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Org_Wallet__c/fields/XRPWebhookSubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookSubscriptionId__c</fullName>
    <label>XRPWebhookSubscriptionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConnectionOrgWalletCtrl.cls
public with sharing class ConnectionOrgWalletCtrl {
    @AuraEnabled
    public static void connectWallet(Id recordId){
        try {
            Org_Wallet__c orgWallet = [SELECT Wallet_Address__c FROM Org_Wallet__c WHERE Id = :recordId];
            XrpWebhookService.RegisterSubscriptionResponse response = XrpWebhookService.subscribeToAddress(orgWallet.Wallet_Address__c);

            orgWallet.XRPWebhookSubscriptionId__c = response.subscription_id;
            update as user orgWallet;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void disConnectWallet(Id recordId){
        try {
            Org_Wallet__c orgWallet = [SELECT XRPWebhookSubscriptionId__c FROM Org_Wallet__c WHERE Id = :recordId];

            if(orgWallet.XRPWebhookSubscriptionId__c != null) {
                XrpWebhookService.removeSubscriptionToAddress(orgWallet.XRPWebhookSubscriptionId__c);
            }

            orgWallet.XRPWebhookSubscriptionId__c = null;
            update as user orgWallet;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}