force-app/main/default/objects/Org_Wallet__c/Org_Wallet__c.object-meta.xml
<CustomObject>
    <description>Organization&apos;s Web3 Digital Wallet</description>
    <label>Org Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Wallets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Wallet__c/fields/Wallet_Address__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Address__c</fullName>
    <description>Publicly available address.</description>
    <label>Wallet Address</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Org_Wallet__c/fields/XRPWebhookSubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>XRPWebhookSubscriptionId__c</fullName>
    <label>XRPWebhookSubscriptionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgWalletSelector.cls
public with sharing class OrgWalletSelector {
    public static Org_Wallet__c getOrgWalletById(Id recordId) {
        List<Org_Wallet__c> wallets = [
            SELECT Wallet_Address__c, XRPWebhookSubscriptionId__c
            FROM Org_Wallet__c
            WHERE Id = :recordId
            WITH USER_MODE
        ];

        return wallets.isEmpty() ? null : wallets[0];
    }

    public static List<Org_Wallet__c> getOrgWalletByWalletAddresses(
        Set<String> walletAddresses
    ) {
        return [
            SELECT Wallet_Address__c
            FROM Org_Wallet__c
            WHERE Wallet_Address__c IN :walletAddresses
            WITH USER_MODE
        ];
    }
}